[package]
name = "password"
version = "0.1.0"
edition = "2021"
description = "A command line password generator"
license = "MIT"

[dependencies]
clap = { version="3.1.6", features = ["derive"] }
rand = "0.8.5"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3